sudo: required
language: groovy
services:
  - docker
jdk:
  - oraclejdk8
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd products-api/
  - ./grailsw compile
  - ./grailsw test-app
  - ./gradlew assemble buildDockerImage
  - cd ../purchase-api/
  - ./grailsw compile
  - ./grailsw test-app
  - ./gradlew assemble buildDockerImage
  - cd ../
after_success:
  - bash <(curl -s https://codecov.io/bash)