dist: trusty
os:
  - linux
sudo: required
language: groovy
script:
  - cd products-api
  - ./grailsw test-app
  - cd ../purchase-api
  - ./grailsw test-app
  cd ../
after_success:
  - bash <(curl -s https://codecov.io/bash)
