---
server:
  port: 8090

---
grails:
    profile: rest-api
    codegen:
        defaultPackage: products.api
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            events: false
info:
    app:
        name: 'eCommerce Products API'
        version: '1.0'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        types:
            json:
              - application/json
              - text/json
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:~/productsDev;MVCC=TRUE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:~/productsTest;MVCC=TRUE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./productsDatabase;MVCC=TRUE