---
server:
  port: 8090

---
grails:
    profile: rest-api
    codegen:
        defaultPackage: products.api
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            events: false
info:
    app:
        name: 'eCommerce Products API'
        version: '0.1'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        types:
            json:
              - application/json
              - text/json
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSourceDevelopment:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
dataSourceProduction:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: commerce
    password: 'commerceapi'
environments:
    development:
        dataSourceDevelopment:
            dbCreate: create-drop
            url: jdbc:h2:~/productsDev;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSourceDevelopment:
            dbCreate: update
            url: jdbc:h2:~/productsTest;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSourceProduction:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/productsapi